name: Swift

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/swift.yml"
      - "Sources/**/*.swift"
      - "Tests/**/*.swift"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/swift.yml"
      - "Sources/**/*.swift"
      - "Tests/**/*.swift"

jobs:
  build:
    runs-on: macos-15

    env:
      SWIFT_VERSION: 6

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Up Swift 6.2
      run: sudo xcode-select -s "/Applications/Xcode_26.0.0.app"
    - name: Swift version
      run: swift --version

    - name: Cache Swift Package Manager Thingys
      uses: actions/cache@v4
      with:
        path: |
          .build
          .swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}-${{ env.TOOLCHAINS }}

    - name: Install invoke
      run: brew install pyinvoke

    - name: Lint
      run: invoke lint
    - name: Run tests
      run: invoke test
