name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Up Swift to use latest v6
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: 6
    - name: Swift version
      run: swift --version

    - name: Install invoke
      run: brew install pyinvoke

    - name: Lint
      run: invoke lint
    - name: Run tests
      run: invoke test
